<a href="https://colab.research.google.com/github/marialabadi/big-data/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from urllib.parse import urljoin

print("Libraries imported successfully!")

Libraries imported successfully!

In [49]:
# تحديد الموقع الأساسي للموقع وإنشاء User-Agent للتعريف بالطلب ثم طباعة الرابط
BASE_URL = "https://en.wikiquote.org"

headers = {
    "User-Agent": "Mozilla/5.0 (compatible; TP01-Web-Scraping/1.0)"
}

print(BASE_URL)

https://en.wikiquote.org

In [50]:
# تحديد رابط صفحة جميع الصفحات
url = BASE_URL + "/wiki/Special:AllPages"
# إرسال طلب لجلب محتوى الصفحة
response = requests.get(
    url,
    headers=headers,
    timeout=20
)

print("Status code:", response.status_code)
print("HTML length:", len(response.text))

Status code: 200
HTML length: 66123

In [51]:
soup = BeautifulSoup(response.text, "html.parser")

print("Page title:", soup.title.get_text(strip=True))

Page title: All pages - Wikiquote

In [52]:
print(response.text[:5000])

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-disabled vector-feature-custom-font-size-clientpref--excluded vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-not-available skin-thumbsize-clientpref-standard" lang="en" dir="ltr">
<head>
<meta charset="UTF-8">
<title>All pages - Wikiquote</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-disabled vector-feature-custom-font-size-clientpref--excluded vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-not-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikiquotemwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":true,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"247eda56-8bdf-4284-85fd-af1090ce586c","wgCanonicalNamespace":"Special","wgCanonicalSpecialPageName":"Allpages","wgNamespaceNumber":-1,"wgPageName":"Special:AllPages","wgTitle":"AllPages","wgCurRevisionId":0,"wgRevisionId":0,"wgArticleId":0,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Special:AllPages","wgRelevantArticleId":0,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgNoticeProject":"wikiquote","wgConfirmEditCaptchaNeededForGenericEdit":false,"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":true,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":0,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":true,"wgULSLanguageSelectorV2Enabled":true,"wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgCheckUserClientHintsInEditRequest":true,"wgSiteNoticeId":"2.13"};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","mediawiki.special":"ready","oojs-ui-core.styles":"ready","oojs-ui.styles.indicators":"ready","mediawiki.widgets.styles":"ready","oojs-ui-core.icons":"ready","mediawiki.htmlform.ooui.styles":"ready","mediawiki.htmlform.styles":"ready","mediawiki.codex.messagebox.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","ext.dismissableSiteNotice.styles":"ready"};RLPAGEMODULES=["mediawiki.htmlform","mediawiki.htmlform.ooui","mediawiki.widgets","site","mediawiki.page.ready","skins.vector.js","ext.centralNotice.geoIP","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.dismissableSiteNotice"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.dismissableSiteNotice.styles%7Cext.uls.interlangu

In [53]:
# استخراج جميع الروابط الموجودة في صفحة HTML
links = soup.find_all("a", href=True)

print("Number of links:", len(links))

Number of links: 393

In [54]:
# إنشاء قائمة لتخزين روابط صفحات Wikiquote
page_links = []
# المرور على جميع الروابط التي تم العثور عليها
for link in links:
    href = link.get("href")

    if href and href.startswith("/wiki/"):
        if not href.startswith("/wiki/Special:"):
            page_links.append(urljoin(BASE_URL, href))
# حذف الروابط المكررة
page_links = list(dict.fromkeys(page_links))

print("Wikiquote page links found:", len(page_links))
print(page_links[:10])

Wikiquote page links found: 359
['https://en.wikiquote.org/wiki/Main_Page', 'https://en.wikiquote.org/wiki/Wikiquote:Community_Portal', 'https://en.wikiquote.org/wiki/Wikiquote:Village_pump', 'https://en.wikiquote.org/wiki/Help:Contents', 'https://en.wikiquote.org/wiki/Wikiquote:Contact_us', 'https://en.wikiquote.org/wiki/List_of_people_by_name', 'https://en.wikiquote.org/wiki/List_of_literary_works', 'https://en.wikiquote.org/wiki/Category:Proverbs', 'https://en.wikiquote.org/wiki/List_of_films', 'https://en.wikiquote.org/wiki/List_of_television_shows']

In [56]:
# تحديد صفحة لاختبار استخراج البيانات منها
test_url = BASE_URL + "/wiki/Albert_Einstein"
# إرسال طلب لجلب صفحة Albert Einstein
test_response = requests.get(
    test_url,
    headers=headers,
    timeout=20
)
# التأكد من نجاح تحميل الصفحة
print("Status:", test_response.status_code)

Status: 200

In [57]:
# تحويل كود HTML الخاص بالصفحة إلى كائن BeautifulSoup لتحليله
test_soup = BeautifulSoup(test_response.text, "html.parser")

print("Title:", test_soup.title.get_text(strip=True))

Title: Albert Einstein - Wikiquote

In [58]:
# البحث عن جميع الاقتباسات الموجودة داخل وسم blockquote
quotes = test_soup.find_all("blockquote")
# عرض عدد الاقتباسات التي تم العثور عليها
print("Quotes found:", len(quotes))

for q in quotes:
    print(q.get_text(" ", strip=True))

Quotes found: 2
Joe Laitin reports that reporters at Bikini were questioning an army lieutenant about what weapons would be used in the next war. "I dunno," he said, "but in the war after the next war, sure as Hell, they'll be using spears!"
The wording of the statement you have quoted is not my own. Shortly after Hitler came to power in Germany I had an oral conversation with a newspaper man about these matters. Since then my remarks have been elaborated and exaggerated nearly beyond recognition. I cannot in good conscience write down the statement you sent me as my own. The matter is all the more embarrassing to me because I, like yourself, I am predominantly critical concerning the activities, and especially the political activities, through history of the official clergy. Thus, my former statement, even if reduced to my actual words (which I do not remember in detail) gives a wrong impression of my general attitude.

In [62]:
# إنشاء دالة لاستخراج الاقتباسات من صفحة معينة
def extract_quotes(url):
    try:
               # إرسال طلب لجلب محتوى الصفحة
               response = requests.get(
            url,
            headers=headers,
            timeout=20
        )

        if response.status_code != 200:
            return []
# تحويل HTML إلى BeautifulSoup لتحليل محتوى الصفحة
        soup = BeautifulSoup(response.text, "html.parser")

        title = soup.title.get_text(" ", strip=True) if soup.title else ""
 # إنشاء قائمة لتخزين الاقتباسات المستخرجة
        results = []

         # البحث عن عناوين الأقسام في الصفحة
        headings = soup.find_all(["h2", "h3"])
# تحديد ما إذا كنا داخل قسم Quotes
        quotes_section = False
# المرور على العناوين وعناصر القوائم في الصفحة
        for element in soup.find_all(["h2", "h3", "li"]):

       # التحقق من وجود عنوان قسم Quotes
            if element.name in ["h2", "h3"]:
                heading_text = element.get_text(" ", strip=True).lower()
# بدء استخراج الاقتباسات بعد الوصول إلى قسم Quotes
                if "quotes" in heading_text:
                    quotes_section = True
                    continue

                # إيقاف استخراج الاقتباسات عند بداية قسم رئيسي جديد
                if quotes_section and element.name == "h2":
                    quotes_section = False
 # استخراج النصوص الموجودة داخل عناصر القائمة في قسم Quotes
            elif element.name == "li" and quotes_section:

                quote_text = element.get_text(" ", strip=True)
# إضافة الاقتباس إذا كان موجوداً وطوله أكثر من 20 حرفاً
                if quote_text and len(quote_text) > 20:
                    results.append({
                        "source_page": title,
                        "quote": quote_text,
                        "url": url
                    })
 # إرجاع جميع الاقتباسات المستخرجة
        return results
# التعامل مع الأخطاء أثناء تحميل أو تحليل الصفحة
    except Exception as e:
        print("Error:", url, e)
        return []

In [63]:
# استخراج الاقتباسات من صفحة الاختبار
test_quotes = extract_quotes(test_url)
# عرض عدد الاقتباسات التي تم استخراجها
print("Number of extracted quotes:", len(test_quotes))

for item in test_quotes:
    print(item)

Number of extracted quotes: 978
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Everything should be made as simple as possible, but not simpler. Repeated throughout his life (with variants); see: Quote Investigator', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Repeated throughout his life (with variants); see: Quote Investigator', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Un homme heureux est trop content du présent pour trop se soucier de l\'avenir. A happy man is too satisfied with the present to dwell too much on the future. From "Mes Projets d\'Avenir", a French essay written at age 18 for a school exam (18 September 1896). The Collected Papers of Albert Einstein Vol. 1 (1987) Doc. 22.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'A happy man is too satisfied with the present to dwell too much on the future.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'From "Mes Projets d\'Avenir", a French essay written at age 18 for a school exam (18 September 1896). The Collected Papers of Albert Einstein Vol. 1 (1987) Doc. 22.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Autoritätsdusel ist der größte Feind der Wahrheit. Blind obedience to authority is the greatest enemy of truth.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Blind obedience to authority is the greatest enemy of truth.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': "Letter to Jost Winteler (July 8th, 1901), quoted in The Private Lives of Albert Einstein by Roger Highfields and Paul Carter (1993), p. 79 . Einstein had been annoyed that Paul Drude , editor of Annalen der Physik , had dismissed some criticisms Einstein made of Drude's electron theory of metals.", 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Lieber Habicht! / Es herrscht ein weihevolles Stillschweigen zwischen uns, so daß es mir fast wie eine sündige Entweihung vorkommt, wenn ich es jetzt durch ein wenig bedeutsames Gepappel unterbreche... / Was machen Sie denn, Sie eingefrorener Walfisch, Sie getrocknetes, eingebüchstes Stück Seele...? Dear Habicht, / Such a solemn air of silence has descended between us that I almost feel as if I am committing a sacrilege when I break it now with some inconsequential babble... / What are you up to, you frozen whale, you smoked, dried, canned piece of soul...? Opening of a letter to his friend Conrad Habicht in which he describes his four revolutionary Annus Mirabilis papers (18 or 25 May 1905) Doc. 27', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Dear Habicht, / Such a solemn air of silence has descended between us that I almost feel as if I am committing a sacrilege when I break it now with some inconsequential babble... / What are you up to, you frozen whale, you smoked, dried, canned piece of soul...?', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Opening of a letter to his friend Conrad Habicht in which he describes his four revolutionary Annus Mirabilis papers (18 or 25 May 1905) Doc. 27', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'E=mc² The equation originally expressed the equivalence of mass and energy as m = L/c² , which easily translates into the far more well-known E = mc² in Does the Inertia of a Body Depend Upon Its Energy Content? published in the Annalen der Physik (27 September 1905) : "If a body gives off the energy L in the form of radiation, its mass diminishes by L/c²." In a later statement explaining the ideas expressed by this equation, Einstein summarized: "It followed from the special theory of relativity that mass and energy are both but different manifestations of the same thing — a somewhat unfamiliar conception for the average mind. Furthermore, the equation E = mc², in which energy is put equal to mass, multiplied by the square of the velocity of light, showed that very small amounts of mass may be converted into a very large amount of energy and vice versa. The mass and energy were equivalent, according to the formula mentioned before. This was demonstrated by Cockcroft and Walton in 1932, experimentally." Atomic Physics (1948) by the J. Arthur Rank Organisation, Ltd. ( Voice of A. Einstein. )', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'The equation originally expressed the equivalence of mass and energy as m = L/c² , which easily translates into the far more well-known E = mc² in Does the Inertia of a Body Depend Upon Its Energy Content? published in the Annalen der Physik (27 September 1905) : "If a body gives off the energy L in the form of radiation, its mass diminishes by L/c²."', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'In a later statement explaining the ideas expressed by this equation, Einstein summarized: "It followed from the special theory of relativity that mass and energy are both but different manifestations of the same thing — a somewhat unfamiliar conception for the average mind. Furthermore, the equation E = mc², in which energy is put equal to mass, multiplied by the square of the velocity of light, showed that very small amounts of mass may be converted into a very large amount of energy and vice versa. The mass and energy were equivalent, according to the formula mentioned before. This was demonstrated by Cockcroft and Walton in 1932, experimentally." Atomic Physics (1948) by the J. Arthur Rank Organisation, Ltd. ( Voice of A. Einstein. )', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Atomic Physics (1948) by the J. Arthur Rank Organisation, Ltd. ( Voice of A. Einstein. )', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'The mass of a body is a measure of its energy content. Ist die Trägheit eines Körpers von seinem Energieinhalt abhängig? ("Does the inertia of a body depend upon its energy content?") Annalen der Physik 18 , 639-641 (1905). Quoted in Concepts of Mass in Classical and Modern Physics by Max Jammer (1961), p. 177', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Ist die Trägheit eines Körpers von seinem Energieinhalt abhängig? ("Does the inertia of a body depend upon its energy content?")', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Annalen der Physik 18 , 639-641 (1905). Quoted in Concepts of Mass in Classical and Modern Physics by Max Jammer (1961), p. 177', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'We shall, therefore, assume the complete physical equivalence of a gravitational field and a corresponding acceleration of the reference system. Statement of the equivalence principle in Yearbook of Radioactivity and Electronics (1907)', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Statement of the equivalence principle in Yearbook of Radioactivity and Electronics (1907)', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'By a clock we understand anything characterized by a phenomenon passing periodically through identical phases so that we must assume, by the principle of sufficient reason, that all that happens in a given period is identical with all that happens in an arbitrary period. "Principe de relativité" Archives des sciences physiques et naturelles (1910) ser. 4. 29 5-28 pp. 125–244, as quoted by Julian Barbour , "The Nature of Time" (Mar 20, 2009) p. 7, arXiv:0903.3489.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': '"Principe de relativité" Archives des sciences physiques et naturelles (1910) ser. 4. 29 5-28 pp. 125–244, as quoted by Julian Barbour , "The Nature of Time" (Mar 20, 2009) p. 7, arXiv:0903.3489.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Die Natur zeigt uns vom Löwen zwar nur den Schwanz. Aber es ist mir unzweifelhaft, dass der Löwe dazugehört, wenn er sich auch wegen seiner ungeheuren Dimensionen dem Blicke nicht unmittelbar offenbaren kann. Wir sehen ihn nur wie eine Laus, die auf ihm sitzt. Nature shows us only the tail of the lion. But there is no doubt in my mind that the lion belongs with it even if he cannot reveal himself to the eye all at once because of his huge dimension. We see him only the way a louse sitting upon him would. Letter to Heinrich Zangger (10 March 1914), quoted in The Curious History of Relativity by Jean Eisenstaedt (2006), p. 126 . Variant: "Nature shows us only the tail of the lion. But I do not doubt that the lion belongs to it even though he cannot at once reveal himself because of his enormous size." As quoted by Abraham Pais in Subtle is the Lord:The Science and Life of Albert Einstein (1982), p. 235 ISBN 0-192-80672-6', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Nature shows us only the tail of the lion. But there is no doubt in my mind that the lion belongs with it even if he cannot reveal himself to the eye all at once because of his huge dimension. We see him only the way a louse sitting upon him would.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Letter to Heinrich Zangger (10 March 1914), quoted in The Curious History of Relativity by Jean Eisenstaedt (2006), p. 126 .', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Variant: "Nature shows us only the tail of the lion. But I do not doubt that the lion belongs to it even though he cannot at once reveal himself because of his enormous size." As quoted by Abraham Pais in Subtle is the Lord:The Science and Life of Albert Einstein (1982), p. 235 ISBN 0-192-80672-6', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Man begreift schwer beim Erleben dieser "großen Zeit", daß man dieser verrückten, verkommenen Spezies angehört, die sich Willensfreiheit zuschreibt. Wenn es doch irgendwo eine Insel der Wohlwollenden und Besonnenen gäbe! Da wollte ich auch glühender Patriot sein. In living through this "great epoch," it is difficult to reconcile oneself to the fact that one belongs to that mad, degenerate species that boasts of its free will. How I wish that somewhere there existed an island for those who are wise and of good will! In such a place even I should be an ardent patriot! Letter to Paul Ehrenfest , early December 1914. Collected Papers of Albert Einstein , Vol. 8, Doc. 39. Quoted in The New Quotable Einstein by Alice Calaprice (2005), p. 3', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'In living through this "great epoch," it is difficult to reconcile oneself to the fact that one belongs to that mad, degenerate species that boasts of its free will. How I wish that somewhere there existed an island for those who are wise and of good will! In such a place even I should be an ardent patriot!', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Letter to Paul Ehrenfest , early December 1914. Collected Papers of Albert Einstein , Vol. 8, Doc. 39. Quoted in The New Quotable Einstein by Alice Calaprice (2005), p. 3', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': "Es ist bequem mit dem Einstein. Jedes Jahr widerruft er, was er das vorige Jahr geschrieben hat. It's convenient with that fellow Einstein, every year he retracts what he wrote the year before. Letter to Paul Ehrenfest, 26 December 1915. Collected Papers of Albert Einstein , Vol. 8, Doc. 173.", 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': "It's convenient with that fellow Einstein, every year he retracts what he wrote the year before.", 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Letter to Paul Ehrenfest, 26 December 1915. Collected Papers of Albert Einstein , Vol. 8, Doc. 173.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'How does it happen that a properly endowed natural scientist comes to concern himself with epistemology ? Is there not some more valuable work to be done in his specialty? That\'s what I hear many of my colleagues ask, and I sense it from many more. But I cannot share this sentiment. When I think about the ablest students whom I have encountered in my teaching — that is, those who distinguish themselves by their independence of judgment and not just their quick-wittedness — I can affirm that they had a vigorous interest in epistemology. They happily began discussions about the goals and methods of science, and they showed unequivocally, through tenacious defense of their views, that the subject seemed important to them. Concepts that have proven useful in ordering things easily achieve such authority over us that we forget their earthly origins and accept them as unalterable givens. [ Begriffe, welche sich bei der Ordnung der Dinge als nützlich erwiesen haben, erlangen über uns leicht eine solche Autorität, dass wir ihres irdischen Ursprungs vergessen und sie als unabänderliche Gegebenheiten hinnehmen. ] Thus they might come to be stamped as "necessities of thought," "a priori givens," etc. The path of scientific progress is often made impassable for a long time by such errors. [ Der Weg des wissenschaftlichen Fortschritts wird durch solche Irrtümer oft für längere Zeit ungangbar gemacht .] Therefore it is by no means an idle game if we become practiced in analysing long-held commonplace concepts and showing the circumstances on which their justification and usefulness depend, and how they have grown up, individually, out of the givens of experience. Thus their excessive authority will be broken. They will be removed if they cannot be properly legitimated, corrected if their correlation with given things be far too superfluous, or replaced if a new system can be established that we prefer for whatever reason. Obituary for physicist and philosopher Ernst Mach ( Nachruf auf Ernst Mach ), Physikalische Zeitschrift 17 (1916), p. 101', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Obituary for physicist and philosopher Ernst Mach ( Nachruf auf Ernst Mach ), Physikalische Zeitschrift 17 (1916), p. 101', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': '...to the question whether or not the motion of the Earth in space can be made perceptible in terrestrial experiments. We have already remarked... that all attempts of this nature led to a negative result. Before the theory of relativity was put forward, it was difficult to become reconciled to this negative result. Relativity – The Special and General Theory (1916), Part I: The Special Theory of Relativity, Experience and the Special Theory of Relativity', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Relativity – The Special and General Theory (1916), Part I: The Special Theory of Relativity, Experience and the Special Theory of Relativity', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Unser ganzer gepriesener Fortschritt der Technik, überhaupt die Civilisation, ist der Axt in der Hand des pathologischen Verbrechers vergleichbar. Our entire much-praised technological progress, and civilization generally, could be compared to an axe in the hand of a pathological criminal. Letter to Heinrich Zangger (1917), as quoted in A Sense of the Mysterious: Science and the Human Spirit by Alan Lightman (2005), p. 110 , and in Albert Einstein: A Biography by Albrecht Fölsing (1997), p. 399 Sometimes paraphrased as "Technological progress is like an axe in the hands of a pathological criminal."', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Our entire much-praised technological progress, and civilization generally, could be compared to an axe in the hand of a pathological criminal.', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Letter to Heinrich Zangger (1917), as quoted in A Sense of the Mysterious: Science and the Human Spirit by Alan Lightman (2005), p. 110 , and in Albert Einstein: A Biography by Albrecht Fölsing (1997), p. 399', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Sometimes paraphrased as "Technological progress is like an axe in the hands of a pathological criminal."', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'The most beautiful fate of a physical theory is to point the way to the establishment of a more inclusive theory, in which it lives on as a limiting case. (1917) as quoted by Gerald Holton , The Advancement of Science, and Its Burdens: the Jefferson Lecture and Other Essays (1986)', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': '(1917) as quoted by Gerald Holton , The Advancement of Science, and Its Burdens: the Jefferson Lecture and Other Essays (1986)', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Ich habe auch manchen wissenschaftlichen Plan überlegt, während ich Dich im Kinderwagen spazieren schob! I have also considered many scientific plans during my pushing you around in your pram! Letter to his son Hans Albert Einstein (June 1918)', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'I have also considered many scientific plans during my pushing you around in your pram!', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': 'Letter to his son Hans Albert Einstein (June 1918)', 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}
{'source_page': 'Albert Einstein - Wikiquote', 'quote': "Geh Recht viel spazieren, dass Du Recht gesund wirst und lies nicht gar zu viel sondern spar Dir noch was auf bis Du gross bist. Make a lot of walks to get healthy and don't read that much but save yourself some until you're grown up. Letter to his son Eduard Einstein (June 1918)", 'url': 'https://en.wikiquote.org/wiki/Albert_Einstein'}

In [64]:
# إنشاء قائمة لتخزين جميع الاقتباسات المستخرجة
all_quotes = []

# المرور على أول 100 صفحة من الموقع
for i, url in enumerate(page_links[:100], start=1):
   # عرض رقم الصفحة التي تتم معالجتها
    print(f"Processing page {i}/100")
    # استخراج الاقتباسات من الصفحة الحالية
    quotes = extract_quotes(url)
   # إضافة الاقتباسات المستخرجة إلى القائمة الرئيسية
    all_quotes.extend(quotes)

    time.sleep(0.5)

print("Total quotes collected:", len(all_quotes))

Processing page 1/100
Processing page 2/100
Processing page 3/100
Processing page 4/100
Processing page 5/100
Processing page 6/100
Processing page 7/100
Processing page 8/100
Processing page 9/100
Processing page 10/100
Processing page 11/100
Processing page 12/100
Processing page 13/100
Processing page 14/100
Processing page 15/100
Processing page 16/100
Processing page 17/100
Processing page 18/100
Processing page 19/100
Processing page 20/100
Processing page 21/100
Processing page 22/100
Processing page 23/100
Processing page 24/100
Processing page 25/100
Processing page 26/100
Processing page 27/100
Processing page 28/100
Processing page 29/100
Processing page 30/100
Processing page 31/100
Processing page 32/100
Processing page 33/100
Processing page 34/100
Processing page 35/100
Processing page 36/100
Processing page 37/100
Processing page 38/100
Processing page 39/100
Processing page 40/100
Processing page 41/100
Processing page 42/100
Processing page 43/100
Processing page 44/100
Processing page 45/100
Processing page 46/100
Processing page 47/100
Processing page 48/100
Processing page 49/100
Processing page 50/100
Processing page 51/100
Processing page 52/100
Processing page 53/100
Processing page 54/100
Processing page 55/100
Processing page 56/100
Processing page 57/100
Processing page 58/100
Processing page 59/100
Processing page 60/100
Processing page 61/100
Processing page 62/100
Processing page 63/100
Processing page 64/100
Processing page 65/100
Processing page 66/100
Processing page 67/100
Processing page 68/100
Processing page 69/100
Processing page 70/100
Processing page 71/100
Processing page 72/100
Processing page 73/100
Processing page 74/100
Processing page 75/100
Processing page 76/100
Processing page 77/100
Processing page 78/100
Processing page 79/100
Processing page 80/100
Processing page 81/100
Processing page 82/100
Processing page 83/100
Processing page 84/100
Processing page 85/100
Processing page 86/100
Processing page 87/100
Processing page 88/100
Processing page 89/100
Processing page 90/100
Processing page 91/100
Processing page 92/100
Processing page 93/100
Processing page 94/100
Processing page 95/100
Processing page 96/100
Processing page 97/100
Processing page 98/100
Processing page 99/100
Processing page 100/100
Total quotes collected: 924

In [65]:
print("Current number of quotes:", len(all_quotes))

Current number of quotes: 924

In [67]:
all_quotes.extend(more_quotes)

print("Final number of quotes:", len(all_quotes))

Final number of quotes: 1258

In [8]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# رابط موقع Wikiquote
BASE_URL = "https://en.wikiquote.org"

# إعداد User-Agent حتى يتعرف الموقع على الطلب
headers = {
    "User-Agent": "Mozilla/5.0 (compatible; TP01-Web-Scraping/1.0)"
}

# تحميل صفحة AllPages
url = BASE_URL + "/wiki/Special:AllPages"

response = requests.get(
    url,
    headers=headers,
    timeout=20
)

# تحويل HTML إلى BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

# استخراج جميع الروابط
links = soup.find_all("a", href=True)

# إنشاء قائمة روابط صفحات Wikiquote
page_links = []

for link in links:
    href = link.get("href")

    if href and href.startswith("/wiki/"):
        if not href.startswith("/wiki/Special:"):
            page_links.append(urljoin(BASE_URL, href))

# حذف الروابط المكررة
page_links = list(dict.fromkeys(page_links))

print("Number of page links:", len(page_links))
print("First 10 links:")
print(page_links[:10])

Number of page links: 359
First 10 links:
['https://en.wikiquote.org/wiki/Main_Page', 'https://en.wikiquote.org/wiki/Wikiquote:Community_Portal', 'https://en.wikiquote.org/wiki/Wikiquote:Village_pump', 'https://en.wikiquote.org/wiki/Help:Contents', 'https://en.wikiquote.org/wiki/Wikiquote:Contact_us', 'https://en.wikiquote.org/wiki/List_of_people_by_name', 'https://en.wikiquote.org/wiki/List_of_literary_works', 'https://en.wikiquote.org/wiki/Category:Proverbs', 'https://en.wikiquote.org/wiki/List_of_films', 'https://en.wikiquote.org/wiki/List_of_television_shows']

In [68]:
df = pd.DataFrame(all_quotes)

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

df.head(10)

Number of rows: 1258
Number of columns: 3

,source_page,quote,url
0,Ezra Klein - Wikiquote,If you are trying to create things that are go...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
1,Ezra Klein - Wikiquote,https://conversationswithtyler.com/episodes/ez...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
2,Ezra Klein - Wikiquote,There is no more profound human bias than the ...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
3,Ezra Klein - Wikiquote,"This Changes Everything (March 13, 2023), The ...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
4,Ezra Klein - Wikiquote,I have called the Republican Party an engine f...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
5,Ezra Klein - Wikiquote,Transcript: Ezra Klein Interviews Sam Rosenfel...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
6,Ezra Klein - Wikiquote,The Democratic Party does not need to choose t...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
7,Ezra Klein - Wikiquote,""" This Is the Way You Beat Trump — and Trumpis...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
8,"""Good chap"" theory - Wikiquote",The nature of its constitution tells you a gre...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
9,"""Good chap"" theory - Wikiquote","Blick, Andrew (2019) . ""Good Chaps No More"". S...",https://en.wikiquote.org/wiki/%22Good_chap%22_...

In [69]:
assert len(df) >= 1000

print("Requirement satisfied!")
print("Final number of rows:", len(df))

Requirement satisfied!
Final number of rows: 1258

In [70]:
df.to_csv(
    "quotes.csv",
    index=False,
    encoding="utf-8-sig"
)

print("quotes.csv saved successfully!")

quotes.csv saved successfully!

In [71]:
import os

print("File exists:", os.path.exists("quotes.csv"))
print("File size:", os.path.getsize("quotes.csv"), "bytes")

File exists: True
File size: 454037 bytes

In [72]:
df_check = pd.read_csv("quotes.csv")

print("Rows in CSV:", len(df_check))
print("Columns:", df_check.columns.tolist())

df_check.head(10)

Rows in CSV: 1258
Columns: ['source_page', 'quote', 'url']

,source_page,quote,url
0,Ezra Klein - Wikiquote,If you are trying to create things that are go...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
1,Ezra Klein - Wikiquote,https://conversationswithtyler.com/episodes/ez...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
2,Ezra Klein - Wikiquote,There is no more profound human bias than the ...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
3,Ezra Klein - Wikiquote,"This Changes Everything (March 13, 2023), The ...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
4,Ezra Klein - Wikiquote,I have called the Republican Party an engine f...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
5,Ezra Klein - Wikiquote,Transcript: Ezra Klein Interviews Sam Rosenfel...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
6,Ezra Klein - Wikiquote,The Democratic Party does not need to choose t...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
7,Ezra Klein - Wikiquote,""" This Is the Way You Beat Trump — and Trumpis...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
8,"""Good chap"" theory - Wikiquote",The nature of its constitution tells you a gre...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
9,"""Good chap"" theory - Wikiquote","Blick, Andrew (2019) . ""Good Chaps No More"". S...",https://en.wikiquote.org/wiki/%22Good_chap%22_...

In [73]:
# Remove empty quotes
df_clean = df[df["quote"].notna()].copy()

# Remove quotes that are actually URLs
df_clean = df_clean[
    ~df_clean["quote"].str.strip().str.startswith(("http://", "https://"))
]

# Remove very short entries
df_clean = df_clean[
    df_clean["quote"].str.len() >= 30
]

# Remove duplicate quotes
df_clean = df_clean.drop_duplicates(subset=["quote"])

# Reset index
df_clean = df_clean.reset_index(drop=True)

print("Rows after cleaning:", len(df_clean))

Rows after cleaning: 1102

In [74]:
df_clean.head(20)

,source_page,quote,url
0,Ezra Klein - Wikiquote,If you are trying to create things that are go...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
1,Ezra Klein - Wikiquote,There is no more profound human bias than the ...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
2,Ezra Klein - Wikiquote,"This Changes Everything (March 13, 2023), The ...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
3,Ezra Klein - Wikiquote,I have called the Republican Party an engine f...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
4,Ezra Klein - Wikiquote,Transcript: Ezra Klein Interviews Sam Rosenfel...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
5,Ezra Klein - Wikiquote,The Democratic Party does not need to choose t...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
6,Ezra Klein - Wikiquote,""" This Is the Way You Beat Trump — and Trumpis...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
7,"""Good chap"" theory - Wikiquote",The nature of its constitution tells you a gre...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
8,"""Good chap"" theory - Wikiquote","Blick, Andrew (2019) . ""Good Chaps No More"". S...",https://en.wikiquote.org/wiki/%22Good_chap%22_...
9,"""Good chap"" theory - Wikiquote",Margaret Thatcher's former press secretary Sir...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
10,"""Good chap"" theory - Wikiquote","""The theory of the ""good chap"" , BBC News (17 ...",https://en.wikiquote.org/wiki/%22Good_chap%22_...
11,"""Good chap"" theory - Wikiquote",But the real “trouble” lies in the consequence...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
12,"""Good chap"" theory - Wikiquote","""Peter Hennessy: Boris Johnson has killed off ...",https://en.wikiquote.org/wiki/%22Good_chap%22_...
13,Edward Whittemore - Wikiquote,But to Stern at that moment it wasn't a hand g...,https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
14,Edward Whittemore - Wikiquote,The Great Jerusalem Poker Game for secret cont...,https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
15,Edward Whittemore - Wikiquote,"Chapter 1, ""Jerusalem 1933,"" opening paragraph...",https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
16,Edward Whittemore - Wikiquote,"""Now I think you'll both agree that through my...",https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
17,Edward Whittemore - Wikiquote,Why is it the Mongols of this world always tel...,https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
18,Edward Whittemore - Wikiquote,"NS is the third book in the ""Jerusalem Quartet""",https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
19,"""Polish death camp"" controversy - Wikiquote","On May 28 of last year, President Obama stood ...",https://en.wikiquote.org/wiki/%22Polish_death_...

In [75]:
print(df_clean["quote"].tolist()[:10])

['If you are trying to create things that are going to be continuously relevant three months from now, eight months from now, a year from now, five years from now, putting more emphasis on the history of a conflict like in Syria, is going to give you a better chance of having something that can be profitably rediscovered going forward. https://conversationswithtyler.com/episodes/ezra-klein/', 'There is no more profound human bias than the expectation that tomorrow will be like today. It is a powerful heuristic tool because it is almost always correct. This Changes Everything (March 13, 2023), The New York Times', 'This Changes Everything (March 13, 2023), The New York Times', 'I have called the Republican Party an engine for turning social resentment into tax cuts. Transcript: Ezra Klein Interviews Sam Rosenfeld and Daniel Schlozman (June 4, 2024), The Ezra Klein Show', 'Transcript: Ezra Klein Interviews Sam Rosenfeld and Daniel Schlozman (June 4, 2024), The Ezra Klein Show', 'The Democratic Party does not need to choose to be one thing. It needs to choose to be more things. " This Is the Way You Beat Trump — and Trumpism " (November 2, 2025), \' The New York Times , as quoted in Henry Farrell, " Liberalism transforms plurality from weakness to strength " (November 3, 2025), Programmable Mutter', '" This Is the Way You Beat Trump — and Trumpism " (November 2, 2025), \' The New York Times , as quoted in Henry Farrell, " Liberalism transforms plurality from weakness to strength " (November 3, 2025), Programmable Mutter', 'The nature of its constitution tells you a great deal about a country, its society and the way ruling power is calibrated and constrained within it. A key characteristic of the British constitution is the degree to which the good governance of the United Kingdom (UK) has relied on the self-restraint of those who carry it out. Unlike nearly every other democracy in the world, we lack a ‘written’ or ‘codified’ constitution. The UK has, therefore, no single text setting out the core principles, institutions and procedures of the system, protected from casual alteration by amendment procedures, and enforceable by the judiciary. Instead, in the UK, we have trusted politicians to behave themselves. We have long assumed that those who rise to high office will be ‘good chaps’, knowing what the unwritten rules are and wanting to adhere to them , even if doing so might frustrate the attainment of their policy objectives, party political goals, or personal ambitions – the argument being that ‘good chaps’ (of different sexes) know where the undrawn lines lie and come nowhere near to crossing them: hence ‘the good chap theory of government. Blick, Andrew (2019) . "Good Chaps No More". Safeguarding the Constitution in Stressful Times : 5–6.', 'Blick, Andrew (2019) . "Good Chaps No More". Safeguarding the Constitution in Stressful Times : 5–6.', 'Margaret Thatcher\'s former press secretary Sir Bernard Ingham\'s memoirs were deemed fair as they came after she had left power and events had moved on. Sir Christopher Meyer\'s were not because they dealt with individuals still in post and issues still running. Good chaps would see that, others might not. "The theory of the "good chap" , BBC News (17 November, 2005)']

In [76]:
print("Number of cleaned rows:", len(df_clean))

for i, quote in enumerate(df_clean["quote"].head(30), start=1):
    print(f"{i}. {quote}")
    print("-" * 80)

Number of cleaned rows: 1102
1. If you are trying to create things that are going to be continuously relevant three months from now, eight months from now, a year from now, five years from now, putting more emphasis on the history of a conflict like in Syria, is going to give you a better chance of having something that can be profitably rediscovered going forward. https://conversationswithtyler.com/episodes/ezra-klein/
--------------------------------------------------------------------------------
2. There is no more profound human bias than the expectation that tomorrow will be like today. It is a powerful heuristic tool because it is almost always correct. This Changes Everything (March 13, 2023), The New York Times
--------------------------------------------------------------------------------
3. This Changes Everything (March 13, 2023), The New York Times
--------------------------------------------------------------------------------
4. I have called the Republican Party an engine for turning social resentment into tax cuts. Transcript: Ezra Klein Interviews Sam Rosenfeld and Daniel Schlozman (June 4, 2024), The Ezra Klein Show
--------------------------------------------------------------------------------
5. Transcript: Ezra Klein Interviews Sam Rosenfeld and Daniel Schlozman (June 4, 2024), The Ezra Klein Show
--------------------------------------------------------------------------------
6. The Democratic Party does not need to choose to be one thing. It needs to choose to be more things. " This Is the Way You Beat Trump — and Trumpism " (November 2, 2025), ' The New York Times , as quoted in Henry Farrell, " Liberalism transforms plurality from weakness to strength " (November 3, 2025), Programmable Mutter
--------------------------------------------------------------------------------
7. " This Is the Way You Beat Trump — and Trumpism " (November 2, 2025), ' The New York Times , as quoted in Henry Farrell, " Liberalism transforms plurality from weakness to strength " (November 3, 2025), Programmable Mutter
--------------------------------------------------------------------------------
8. The nature of its constitution tells you a great deal about a country, its society and the way ruling power is calibrated and constrained within it. A key characteristic of the British constitution is the degree to which the good governance of the United Kingdom (UK) has relied on the self-restraint of those who carry it out. Unlike nearly every other democracy in the world, we lack a ‘written’ or ‘codified’ constitution. The UK has, therefore, no single text setting out the core principles, institutions and procedures of the system, protected from casual alteration by amendment procedures, and enforceable by the judiciary. Instead, in the UK, we have trusted politicians to behave themselves. We have long assumed that those who rise to high office will be ‘good chaps’, knowing what the unwritten rules are and wanting to adhere to them , even if doing so might frustrate the attainment of their policy objectives, party political goals, or personal ambitions – the argument being that ‘good chaps’ (of different sexes) know where the undrawn lines lie and come nowhere near to crossing them: hence ‘the good chap theory of government. Blick, Andrew (2019) . "Good Chaps No More". Safeguarding the Constitution in Stressful Times : 5–6.
--------------------------------------------------------------------------------
9. Blick, Andrew (2019) . "Good Chaps No More". Safeguarding the Constitution in Stressful Times : 5–6.
--------------------------------------------------------------------------------
10. Margaret Thatcher's former press secretary Sir Bernard Ingham's memoirs were deemed fair as they came after she had left power and events had moved on. Sir Christopher Meyer's were not because they dealt with individuals still in post and issues still running. Good chaps would see that, others might not. "The theory of the "good chap" , BBC News (17 November, 2005)
--------------------------------------------------------------------------------
11. "The theory of the "good chap" , BBC News (17 November, 2005)
--------------------------------------------------------------------------------
12. But the real “trouble” lies in the consequences of “a prime minister ( Boris Johnson ) who is absolutely tone deaf to all the niceties of this. He hasn’t got a single feel for either proper behaviour, proper procedure, not a single nerve end. He has got no sense of the restraints you need to make this work. If a bit of it annoys him or gets in his way, he tries to cast it aside. "Peter Hennessy: Boris Johnson has killed off the “good chaps” theory of government" , Prospect (January 21, 2022)
--------------------------------------------------------------------------------
13. "Peter Hennessy: Boris Johnson has killed off the “good chaps” theory of government" , Prospect (January 21, 2022)
--------------------------------------------------------------------------------
14. But to Stern at that moment it wasn't a hand grenade at all but a no longer distant cloud high above the Temple of the Moon, a driftin memory in the desert of dim pillars and fountains and waterways, mysterious places where myrrh grew, the ruins of his youth. Blinding light then in the mirror behind the bar, sudden death merging the stars and windstorms of his life with darkness in the failure of his seeking, bright blinding light in the night sky at last and Stern's once vast vision of a homeland for all the peoples of his heritage gone as if he had never lived, shattered as if he had never suffered, his futile devotion ended on a clear Cairo night during the uncertain campaigns of 1942 when the eternal disguise he wore to his last clandestine meeting, his face, was ripped way and thrown against a mirror in the half-light of an Arab bar, there to stare at a now immobile landscape fixed to witness his death forever.
--------------------------------------------------------------------------------
15. The Great Jerusalem Poker Game for secret control of the city, the ruin of so many adventurers in the period between the two world wars, continued for twelve years before it finally spent itself. During that time thousands of gamblers from around the world lost fortunes trying to win the Holy City, but in the end there were only three men at the table, the same three who had been there in the beginning. Chapter 1, "Jerusalem 1933," opening paragraph of novel.
--------------------------------------------------------------------------------
16. Chapter 1, "Jerusalem 1933," opening paragraph of novel.
--------------------------------------------------------------------------------
17. "Now I think you'll both agree that through my various illicit enterprises," Cairo Martyr said, "I control the Moslem Quarter in this city." "The mummy dust king is about to strike," muttered O'Sullivan Beare. But at the same time he knew the claim was true, just as was his own secret control over the Christian Quarter and Munk Szondi's over the Jewish Quarter, religious symbols and trading in futures being just as essential to Jerusalem as mummy dust. "Now then, that's my bet. Control of the Moslem Quarter. I'm putting the Moslem Quarter on the table. If either of you wins, which you won't, it belongs to you. But first you have to match my bet. No openers. The real thing." Chapter 1, "Jerusalem 1933"
--------------------------------------------------------------------------------
18. Why is it the Mongols of this world always tell us they're defending us against the Mongols? NS is the third book in the "Jerusalem Quartet"
--------------------------------------------------------------------------------
19. NS is the third book in the "Jerusalem Quartet"
--------------------------------------------------------------------------------
20. On May 28 of last year, President Obama stood next to Prime Minister Donald Tusk of Poland in Warsaw and declared he would support new rules to help more Poles get tourist visas to the United States. “If you’ve lived in Chicago and you haven’t become a little bit Polish,” Mr. Obama joked, “there’s something wrong with you.” A year later, the president made himself the target of a searing denunciation by Mr. Tusk after he referred on Tuesday to a “Polish death camp,” instead of a Nazi death camp in Poland, in bestowing a Presidential Medal of Freedom on Jan Karski , a hero of the Polish resistance to the Germans during World War II. Mr. Obama was guilty of “ignorance, lack of knowledge, bad intentions,” Mr. Tusk said. Mark Landler , " Premier Denounces Obama for Referring to a ‘Polish Death Camp’ " in nytimes.com . Published: May 30, 2012.
--------------------------------------------------------------------------------
21. Mark Landler , " Premier Denounces Obama for Referring to a ‘Polish Death Camp’ " in nytimes.com . Published: May 30, 2012.
--------------------------------------------------------------------------------
22. Alanis Morissette and I actually used to date. I especially liked it when we went to the movies. AL TV , MTV, 1996; referring to the line "Is she perverted like me/would she go down on you in a theater" from Morissette's breakout hit You Oughta Know .
--------------------------------------------------------------------------------
23. AL TV , MTV, 1996; referring to the line "Is she perverted like me/would she go down on you in a theater" from Morissette's breakout hit You Oughta Know .
--------------------------------------------------------------------------------
24. That's something the kids should know about. Reading is a gateway to witchcraft and lesbianism. I Love the 90's Part Deux , VH1, 1998; referring to Willow Rosenberg from Buffy the Vampire Slayer .
--------------------------------------------------------------------------------
25. I Love the 90's Part Deux , VH1, 1998; referring to Willow Rosenberg from Buffy the Vampire Slayer .
--------------------------------------------------------------------------------
26. I wrote " Eat It " because I wanted to buy a banana boat for Christmas. It worked. I Love the 80's 3D , VH1, 1985.
--------------------------------------------------------------------------------
27. I Love the 80's 3D , VH1, 1985.
--------------------------------------------------------------------------------
28. I have very mixed feelings about [Napster]. On one hand, I'm concerned that the rampant downloading of my copyright-protected material over the Internet is severely eating into my album sales and having a decidedly adverse effect on my career. On the other hand, I can get all the Metallica songs I want for FREE! WOW!!!!! Ask Al Archives: May 2000 .
--------------------------------------------------------------------------------
29. What kind of bananas do you have working at newspapers in Austin that would base an entire review of an artist's performance on whether or not they had a good seat? Replying to a fan criticizing the poor seats a reviewer of a concert received. "Ask Al" Q&As for September 6, 2004 .
--------------------------------------------------------------------------------
30. Replying to a fan criticizing the poor seats a reviewer of a concert received. "Ask Al" Q&As for September 6, 2004 .
--------------------------------------------------------------------------------

In [77]:
import re

df_final = df_clean.copy()

# Remove entries that look like references/sources rather than quotations
reference_patterns = [
    r"^This Changes Everything\s*\(",
    r"^Transcript:",
    r"^Blick, Andrew\s*\(",
    r"^Chapter \d+",
    r"^NS is the third book",
    r"^Mark Landler\s*,",
    r"^AL TV\s*,",
    r"^I Love the 90's",
    r"^Replying to a fan",
    r"^Ask Al",
]

pattern = "|".join(reference_patterns)

df_final = df_final[
    ~df_final["quote"].str.strip().str.match(pattern, case=False, na=False)
]

# Remove duplicate quotations
df_final = df_final.drop_duplicates(subset=["quote"])

# Reset index
df_final = df_final.reset_index(drop=True)

print("Final rows:", len(df_final))
print("Columns:", df_final.columns.tolist())

Final rows: 1092
Columns: ['source_page', 'quote', 'url']

In [78]:
df_final.head(20)

,source_page,quote,url
0,Ezra Klein - Wikiquote,If you are trying to create things that are go...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
1,Ezra Klein - Wikiquote,There is no more profound human bias than the ...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
2,Ezra Klein - Wikiquote,I have called the Republican Party an engine f...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
3,Ezra Klein - Wikiquote,The Democratic Party does not need to choose t...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
4,Ezra Klein - Wikiquote,""" This Is the Way You Beat Trump — and Trumpis...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
5,"""Good chap"" theory - Wikiquote",The nature of its constitution tells you a gre...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
6,"""Good chap"" theory - Wikiquote",Margaret Thatcher's former press secretary Sir...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
7,"""Good chap"" theory - Wikiquote","""The theory of the ""good chap"" , BBC News (17 ...",https://en.wikiquote.org/wiki/%22Good_chap%22_...
8,"""Good chap"" theory - Wikiquote",But the real “trouble” lies in the consequence...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
9,"""Good chap"" theory - Wikiquote","""Peter Hennessy: Boris Johnson has killed off ...",https://en.wikiquote.org/wiki/%22Good_chap%22_...
10,Edward Whittemore - Wikiquote,But to Stern at that moment it wasn't a hand g...,https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
11,Edward Whittemore - Wikiquote,The Great Jerusalem Poker Game for secret cont...,https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
12,Edward Whittemore - Wikiquote,"""Now I think you'll both agree that through my...",https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
13,Edward Whittemore - Wikiquote,Why is it the Mongols of this world always tel...,https://en.wikiquote.org/wiki/%22Jerusalem_Pok...
14,"""Polish death camp"" controversy - Wikiquote","On May 28 of last year, President Obama stood ...",https://en.wikiquote.org/wiki/%22Polish_death_...
15,"""Weird Al"" Yankovic - Wikiquote",Alanis Morissette and I actually used to date....,https://en.wikiquote.org/wiki/%22Weird_Al%22
16,"""Weird Al"" Yankovic - Wikiquote",That's something the kids should know about. R...,https://en.wikiquote.org/wiki/%22Weird_Al%22
17,"""Weird Al"" Yankovic - Wikiquote","I wrote "" Eat It "" because I wanted to buy a b...",https://en.wikiquote.org/wiki/%22Weird_Al%22
18,"""Weird Al"" Yankovic - Wikiquote","I Love the 80's 3D , VH1, 1985.",https://en.wikiquote.org/wiki/%22Weird_Al%22
19,"""Weird Al"" Yankovic - Wikiquote",I have very mixed feelings about [Napster]. On...,https://en.wikiquote.org/wiki/%22Weird_Al%22

In [79]:
df_final.to_csv(
    "quotes.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Final CSV saved successfully!")
print("Number of rows:", len(df_final))

Final CSV saved successfully!
Number of rows: 1092

In [80]:
final_check = pd.read_csv("quotes.csv")

print("Rows in CSV:", len(final_check))
print("Columns:", final_check.columns.tolist())
print("Missing values:")
print(final_check.isnull().sum())

Rows in CSV: 1092
Columns: ['source_page', 'quote', 'url']
Missing values:
source_page    0
quote          0
url            0
dtype: int64

In [81]:
final_check.head(10)

,source_page,quote,url
0,Ezra Klein - Wikiquote,If you are trying to create things that are go...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
1,Ezra Klein - Wikiquote,There is no more profound human bias than the ...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
2,Ezra Klein - Wikiquote,I have called the Republican Party an engine f...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
3,Ezra Klein - Wikiquote,The Democratic Party does not need to choose t...,https://en.wikiquote.org/wiki/%22Ezra_Klein%22
4,Ezra Klein - Wikiquote,""" This Is the Way You Beat Trump — and Trumpis...",https://en.wikiquote.org/wiki/%22Ezra_Klein%22
5,"""Good chap"" theory - Wikiquote",The nature of its constitution tells you a gre...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
6,"""Good chap"" theory - Wikiquote",Margaret Thatcher's former press secretary Sir...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
7,"""Good chap"" theory - Wikiquote","""The theory of the ""good chap"" , BBC News (17 ...",https://en.wikiquote.org/wiki/%22Good_chap%22_...
8,"""Good chap"" theory - Wikiquote",But the real “trouble” lies in the consequence...,https://en.wikiquote.org/wiki/%22Good_chap%22_...
9,"""Good chap"" theory - Wikiquote","""Peter Hennessy: Boris Johnson has killed off ...",https://en.wikiquote.org/wiki/%22Good_chap%22_...

In [82]:
from google.colab import files

files.download("quotes.csv")